---

# Install homeshick

- name: install homeshick
  git: repo=git://github.com/andsens/homeshick.git
       dest=~/.homesick/repos/homeshick

- name: check homeshick castle
  shell: ~/.homesick/repos/homeshick/bin/homeshick check dotfiles &>/dev/null; echo $?
  register: homeshick_castle

- name: install homeshick castle
  shell: ~/.homesick/repos/homeshick/bin/homeshick clone https://github.com/burningtree/dotfiles.git -q
  when: homeshick_castle.stdout != "0"

- name: update homeshick
  shell: ~/.homesick/repos/homeshick/bin/homeshick pull -b


